name: Ant-v5
forward_reward_weight: 1.0
ctrl_cost_weight: 0.5
contact_cost_weight: 5e-4
healthy_reward: 1.0
terminate_when_unhealthy: true
healthy_z_range: [0.2, 1.0]
contact_force_range: [-1.0, 1.0]
render_mode: null
max_steps: 1000